### PR TITLE
Submission/edwardyun

### PR DESCRIPTION
**Pull request by birdsome**
The initial problem I ran into with this code was in the feature's description. According to the description, 
changing to the directory that contains index.js and entering http-server test-data in the command line. However, this command didn't work for me. After some work, I have found a better way of connecting to the server. The user should first cd into node_modules/http-server/bin then enter node http-server ../../../test-data
I fixed this by adding the above in the appropriate area of the FeatureOverview file

### CODE REVIEW

**Comment by birdsome** [comment]
The next issue that I ran into was a lack of preparation for a bad request. Whenever I attempted to enter a bad request, instead of getting a 404 message I got a blank page. However, upon further inspection, I think this is an  issue with the module. I don't understand the module well enough to fix this issue but my advice would be to implement the server yourself in sync-server then it would be simpler to implement the 404 response. 
I put in a possible fix in sync_server for the 404 issue, but it is not connected to the 404 image. It is in comments so that you can look at the suggestion and work from there.

**Comment by birdsome** [comment]
Removed my-local-ip from npm modules because it was unused.

**Comment by birdsome** [comment]
It could be useful to find the IP address to put into the url. I would use a similar implementation to what I used in my own feature, however I would implement it in the http-server file. 
I added the ip module requirement and the function that returns ip address in the http-server file and I also used the ip address in the console log statement.

**Comment by birdsome** [comment]
Finally, I found the web interface to be confusing with the exposed hashes. I think finding a way to safely remove this from the module could be beneficial, especially for the lay user. This is something I don't know how to fix myself, so I will add comments of possible suggestions.
I added comments to the http-server.js file around the area that I think the fix should occur, but I do not know enough to fix this.

**Comment by edwardyun14** [comment]
Couldn't pull this into my branch, but I made the necessary changes

**Pull request closed without merging**
